# config
cover: /img/bg_img.jpg
logo: /img/logo_omega.png
top_saying:
- title: Adventure is out there. <span>ç”Ÿæ´»å°±æ˜¯å†’é™©</span>ã€‚
- content: â€”â€” Elie ã€Šé£å±‹ç¯æ¸¸è®°ã€‹
bottom_saying: å¦‚æœä½ çœ‹åˆ°è¿™é‡Œï¼Œç¥ä½ æ¯å¤©éƒ½å¼€å¿ƒã€‚ğŸ˜‰
# Content
excerpt_link: Read More

rss: /404

highlightjs: vs

#Works é¡¹ç›®ç»å†
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo: 

#disqus name
disqus_shortname: Omega

#fancybox
fancybox: true

# Miscellaneous
# github: https://github.com/
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
